# Results

## Model Parameters
The one-way MANOVA reaches significance at either flexion and extension contractions ($X^2 = 73.97, p<0.001$ and $X^2 = 101.02, p<0.001$, respectively).

### Flexion
[Insert Fig.\ \@ref(fig:0dFlexHotelling)]

Nine out of fifteen paired Hotelling's $T^2$ tests conducted on flexion contractions (Fig. 1) reach significance ($p<0.05$).

[Insert Fig.\ \@ref(fig:0dFlexPosthoc)]

Three additional paired t-tests applied on P1 reach significance, zero on P2, three on P3, four on P4, five on P5, two on P6 and four on P7 (details on each comparison available in Fig. 2).

### Extension
[Insert Fig.\ \@ref(fig:0dExtHotelling)]

Thirteen out of fifteen paired Hotelling's $T^2$ tests conducted on extension contractions (Fig. 3) reach significance ($p<0.05$).

[Insert Fig.\ \@ref(fig:0dExtPosthoc)]

Eight additional paired t-tests applied on P1 reach significance, zero on P2, seven on P3, five on P4, five on P5, two on P6 and nine on P7 (details on each comparison available in Fig. 4).

## Torque-Angle-Velocity Model

### Flexion
[Insert Fig.\ \@ref(fig:1dFlexAnova)]

The main effect of position from the one-way ANOVA (Fig. 5) reaches significance ($p<0.05$) in the area that includes angles around 90^o^ (from 68 to 123^o^) and high positive velocities (from 75 to 180 ^o^$.\text{s}^{-1}$).
The F-value is constant in this significant area (from 4 to 6).

[Insert Fig.\ \@ref(fig:1dFlexPosthoc)]

Only six out of fifteen additional paired t-tests applied on each pair of positions reach significance ($p<0.05$) in the area given by the ANOVA (Fig. 6).
In this area, the elbow torque generated in the F0ER, A90ER and A90IR are significantly lower compared to the F90ER and F180ER positions.
Hence, the elbow torque is greater when the glenohumeral joint is at 90^o^ of flexion compared to other positions during flexion contractions at angles around 90^o^ and at high positive velocities.

### Extension
[Insert Fig.\ \@ref(fig:1dExtAnova)]

The main effect of position from the one-way ANOVA (Fig. 7) reaches significance ($p<0.05$) in every combination of angles and velocity, excluding the area around 90^o^ (from 65 to 86^o^) and low negative velocities (from 0 to -129 ^o^$.\text{s}^{-1}$).
The F-value reaches its maximum (15) around high velocities (100-180) and angles close to 90^o^ (80-110^o^).

[Insert Fig.\ \@ref(fig:1dExtPosthoc)]

Thirteen out of fifteen additional paired t-tests applied on each pair of positions reach significance ($p<0.05$) in the area given by the ANOVA (Fig. 8).
Taken together, these tests suggest that the position's elbow torque generation is in the following order (from greatest to least): F0ER, F90ER, A90IR, F90IR, A90ER, F180ER.
Note that F90ER and A90IR are switched when the angle is below 90^o^.
There is little differences around 90^o^ and most differences appear over the full velocity range (10 out of 15) except F0ER vs A90IR, F180ER vs F90IR, A90ER vs F90IR which occur at high positive velocities.
