# Figures Captions

<!-- 0D -->

Figure\ 1. T statistic of Hotelling's $T^2$ tests conducted on the model parameters of each pair of positions during flexion contractions, with a color gradient associated with the amplitude of the T statistic (empty and white if nonsignificant).
The gray rectangles on the diagonal represent an intersection between the same position.

Figure\ 2. Additional paired t-tests applied on each model parameters (P1 to P7, except P2 which do not reach significance) of each pair of positions during flexion contractions.
A colored rectangle is present when the test reaches significance, with a color gradient associated with the amplitude of the difference in percentage between the pair of positions (purple when the parameter of the position in column is higher, green when the parameter of the position in row is higher).
A description of each position is displayed on the diagonal.

Figure\ 3. T statistic of Hotelling's $T^2$ tests conducted on the model parameters of each pair of positions during extension contractions, with a color gradiant associated with the amplitude of the T statistic (empty and white if non-significant).
The gray rectangles on the diagonal represent an intersection between the same position.

Figure\ 4. Additional paired t-tests applied on each model parameters (P1 to P7, except P2 which do not reach significance) of each pair of positions during extension contractions.
A colored rectangle is present when the test reaches significance, with a color gradient associated with the amplitude of the difference in percentage between the pair of positions (purple when the parameter of the position in column is higher, green when the parameter of the position in row is higher).
A description of each position is displayed on the diagonal.

<!-- 1D -->

Figure\ 5. F-value of the ANOVA applied to the torque-angle-velocity model during flexion contractions. A main effect of position is displayed with a colored rectangle on the X-Y space (angle vs velocity), with a color gradient associated with the amplitude of the F-value.

Figure\ 6. Additional paired t-tests applied on the torque-angle-velocity model of each pair of positions during flexion contractions.
A significant difference is displayed with a colored rectangle on the X-Y space (angle vs velocity), with a color gradient associated with the amplitude of the torque difference between the pair of positions (purple when the parameter of the position in column is higher, green when the parameter of the position in row is higher).
A description of each position is displayed on the diagonal.

Figure\ 7. F-value of the ANOVA applied to the torque-angle-velocity model during extension contractions.
A main effect of position is displayed with a colored rectangle on the X-Y space (angle vs velocity), with a color gradient associated with the amplitude of the F-value.

Figure\ 8. Additional paired t-tests applied on the torque-angle-velocity model of each pair of positions during flexion contractions.
A significant difference is displayed with a colored rectangle on the X-Y space (angle vs velocity), with a color gradient associated with the amplitude of the torque difference between the pair of positions (purple when the parameter of the position in column is higher, green when the parameter of the position in row is higher).
A description of each position is displayed on the diagonal.

<!-- --- -->
